# Generated by Django 3.0.4 on 2020-07-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200702_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_img_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
