# Generated by Django 3.0.4 on 2020-07-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_article_main_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(error_messages={'required': 'Please add some content to the post'}),
        ),
    ]
