# Generated by Django 3.0.4 on 2020-07-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200706_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-dt_creation']},
        ),
    ]
