# Generated by Django 3.0.4 on 2020-04-02 16:29

import common.storage
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/profile_pictures/default.png', storage=common.storage.OverwriteStorage(), upload_to=users.models.ProfileImageSavePath),
        ),
    ]
