# Generated by Django 3.0.4 on 2020-07-06 08:42

import common.storage
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200706_0029'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=common.storage.OverwriteStorage(), upload_to=users.models.profileBannerSavePath),
        ),
        migrations.AddField(
            model_name='profile',
            name='highlight_color_hex',
            field=models.CharField(blank=True, default='000000', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(related_name='saved_by', to='posts.Post'),
        ),
    ]
