# Generated by Django 2.2.3 on 2019-07-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PENDING_REQUEST_BECOME_ADMIN',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='PENDING_REQUEST_BECOME_INSTRUCTOR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='PENDING_REQUEST_PASSWORD_CHANGE',
            field=models.BooleanField(default=False),
        ),
    ]
