# Generated by Django 3.0.4 on 2020-07-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200706_0029'),
        ('users', '0002_auto_20200706_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='posts.Post'),
        ),
    ]
