# Generated by Django 3.0.4 on 2020-07-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-dt_creation']},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-dt_join']},
        ),
    ]
