# Generated by Django 3.0.4 on 2020-04-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='tagline',
            new_name='title',
        ),
    ]
